---
abstract: 'A tiny replacement for Module::Build'
author:
  - 'Leon Timmermans <leont@cpan.org>'
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Carp: 0
  Config: 0
  Cwd: 0
  Data::Dumper: 0
  File::Spec: 0
  File::Temp: 0
  IO::File: 0
  IPC::Open2: 0
  Test::More: 0.88
  XSLoader: 0
  blib: 0
configure_requires:
  CPAN::Meta: 0
  Exporter: 5.57
  ExtUtils::CBuilder: 0
  ExtUtils::Config: 0.003
  ExtUtils::Helpers: 0.020
  ExtUtils::Install: 0
  ExtUtils::InstallPaths: 0.002
  ExtUtils::ParseXS: 0
  File::Basename: 0
  File::Find: 0
  File::Path: 0
  File::Spec::Functions: 0
  Getopt::Long: 0
  JSON::PP: 2
  Pod::Man: 0
  TAP::Harness: 0
  perl: 5.006
  strict: 0
  warnings: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Build-Tiny
requires:
  CPAN::Meta: 0
  Exporter: 5.57
  ExtUtils::CBuilder: 0
  ExtUtils::Config: 0.003
  ExtUtils::Helpers: 0.020
  ExtUtils::Install: 0
  ExtUtils::InstallPaths: 0.002
  ExtUtils::ParseXS: 0
  File::Basename: 0
  File::Find: 0
  File::Path: 0
  File::Spec::Functions: 0
  Getopt::Long: 0
  JSON::PP: 2
  Pod::Man: 0
  TAP::Harness: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Module-Build-Tiny
  repository: git://github.com/Leont/module-build-tiny.git
version: 0.022
