---
abstract: 'A tiny replacement for Module::Build'
author:
  - 'Leon Timmermans <fawaka@gmail.com>'
build_requires:
  Capture::Tiny: 0
  Carp: 0
  Config: 0
  Cwd: 0
  Data::Dumper: 0
  File::Basename: 0
  File::Find: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  File::pushd: 1.00
  IO::File: 0
  Test::More: 0.86
  vars: 0
configure_requires:
  CPAN::Meta: 0
  Exporter: 5.57
  ExtUtils::BuildRC: 0.003
  ExtUtils::Helpers: 0.007
  ExtUtils::Install: 0
  ExtUtils::InstallPaths: 0
  File::Find::Rule: 0
  File::Slurp: 0
  File::Spec::Functions: 0
  Getopt::Long: 0
  JSON::PP: 2
  TAP::Harness: 0
  perl: 5.008
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Build-Tiny
requires:
  CPAN::Meta: 0
  Exporter: 5.57
  ExtUtils::BuildRC: 0.003
  ExtUtils::Helpers: 0.007
  ExtUtils::Install: 0
  ExtUtils::InstallPaths: 0
  File::Find::Rule: 0
  File::Slurp: 0
  File::Spec::Functions: 0
  Getopt::Long: 0
  JSON::PP: 2
  TAP::Harness: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Module-Build-Tiny
  repository: git://github.com/Leont/module-build-tiny.git
version: 0.008
